# Generated by Django 2.1 on 2018-12-20 08:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=4000, verbose_name='Текст статьи')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст комментария')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='webapp.Article', verbose_name='Статья')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('horror', 'Ужасно'), ('bad', 'Плохо'), ('middle', 'Средне'), ('good', 'Хорошо'), ('perfect', 'Отлично')], max_length=20, verbose_name='Оценка')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='webapp.Article', verbose_name='Статья')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favored_by', to='webapp.Article', verbose_name='Избранное')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='webapp.User', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='webapp.User', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='webapp.Comment', verbose_name='Родительский комментарий'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='webapp.User', verbose_name='Автор'),
        ),
    ]
